### ISSUE TITLE
Simplify generator tasks

### ISSUE THREAD

**Issue by jupl** [jupl/btc#13]
Instead of `jake gen:codetest name=controller` something like `jake gen codetest=controller` saves some keystrokes.

**Comment by ghost** [comment]
+1 for this. Would suggest format which follows scaffolt with some
Gruntisms, e.g.

jake gen:codetest testName

**Comment by jupl** [comment]
That was my original plan, but Jake doesn't support that syntax. A nice thing about my suggestion is that it can be written in a way such that one can generate multiple things in a single line. ex: `jake gen model=user view=user controller=user`

**Comment by jupl** [comment]
Plus `jake gen` alone can list available generators. All this also applies to `jake del`.

**Comment by ghost** [comment]
Nice. I didn't realize you could chain the commands for diff generators in
a single statement. That'd be super handy for composite generators.

**Comment by jupl** [comment]
Currently not right now, but it's easy to do. Also simple composite generators are doable with Scaffolt's dependencies option.

**Comment by ghost** [comment]
Thanks for the info. Sounds related to
https://github.com/paulmillr/scaffolt/issues/15. But thinking about it,
it's probably not such a terrible idea to keep things simple. The power of
even individual generators is pretty sweet.

**Comment by jupl** [comment]
Not really. That issue is only when you use the APIs via Node. I'm running them as a shell command so that doesn't happen.

**Comment by ghost** [comment]
Oh, I wasn't paying close enough attention. Thanks for the responsiveness
and explanation. It's very helpful.
