### ISSUE TITLE
Set npm start to assemble app by default?

### ISSUE THREAD

**Issue by jupl** [jupl/btc#18]
Instead of `server:prod`, do `build:prod`

**Comment by ghost** [comment]
It would be confusing to run START and not actually start something, don't you think?

**Comment by jupl** [comment]
The word change may be confusing, I agree. Start would start the build process, though. :P

I am tempted because currently I'm thinking what is the normal use case. I don't think the use case for someone outside of developing the app is to start the server. It may be enough for small internal apps, but I think more things need to be added to be used normally, like SEO support. At that point `npm start` would revert back.

**Comment by ghost** [comment]
Good point. And since it's not a node app my point is moot anyhow. +1

**Comment by jupl** [comment]
Closing now that Prerender is added.
