### ISSUE TITLE
Examine Karma and Jasmine

### ISSUE THREAD

**Issue by jupl** [jupl/btc#7]
Karma can replace Mocha PhantomJS.

Jasmine doesn't have node.js support out of the box, plus creators don't want `beforeAll` nor `afterAll`. Sticking with Mocha.

**Comment by ghost** [comment]
Hey @jupl. The work you've been doing is great and is going to improve the lives of many developers. What do you think about the karma integration @elving put together in [Brunch with Hipsters](https://github.com/elving/brunch-with-hipsters)?

**Comment by jupl** [comment]
Thank you, @jhabdas! I just finished switching over to Karma these past few hours. Overall process does look similar to BWH. The docs should cover it. :)

**Comment by ghost** [comment]
Saweet
